#####使用哪个环境 prod生成环境  dev开发环境########
spring:
  profiles:
    active: dev
##########公共配置##########   
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
########## 静态资源访问配置 ###########
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

  thymeleaf:
    cache: false #开启模板热部署
    mode: HTML #不校验html标签,需要加入jar包 net.sourceforge.nekohtml

########### 邮箱配置 ##############
  mail:
    host: smtp.163.com
    username: pibigstar@163.com
    password:  leikewei521  #邮箱授权码
    default-encoding: UTF-8
    
########### Mybatis 配置  ################
mybatis:
  type-aliases-package: com.pibigstar.parsevip.domain # 实体扫描路径
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名

########### 自定义配置  #############
#######使用：@Value("${mail.sender") #######
#以谁来发送邮件
mail.sender: pibigstar@163.com 
#QQ登录配置  
parsevip.QQLogin.appId: 101472011
parsevip.QQLogin.redirecturi: http://mxspvip.cn/index
#是否开启验证码验证
parsevip.openCode: false  
#首页播放视频链接配置
parsevip.video.src: http://p8b1ddiwd.bkt.clouddn.com/video/sugar.mp4 
#插件安装配置
parsevip.install.src: http://p8b1ddiwd.bkt.clouddn.com/resources/插件安装包.zip
#加群信息配置
#群号
parsevip.qqgroup: 752146272 
#加群链接
parsevip.addgroupUrl: https://shang.qq.com/wpa/qunwpa?idkey=875408aae56499d92ddcdda3966fa7c01e1d3b587b038d335917df7d41893170
#欢迎语
parsevip.welcome: 欢迎加入QQ群：${parsevip.qqgroup}
#后台名字
parsevip.admin.name: VIP资源解析 
#后台前缀
parsevip.admin.address: admin 
#默认头像
parsevip.admin.defaultImg: images/face.jpg 
#开发作者
parsevip.admin.author: java_派大星

