server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    data-username: root
    data-password: 123456
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    
  thymeleaf:
    cache: false #开启模板热部署

