#####使用哪个环境 prod生成环境  dev开发环境########
spring:
  profiles:
    active: dev
##########公共配置##########   
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
#######静态资源访问配置#######
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

  thymeleaf:
    cache: false #开启模板热部署
    
########邮箱配置###########
  mail:
    host: smtp.163.com
    username: pibigstar@163.com
    password:  #邮箱授权码
    default-encoding: UTF-8
mail:
  sender: pibigstar@163.com #以谁来发送邮件

#########################自定义配置#################################
#############使用：${parsevip.QQ.qqgroup}##############################
parsevip:
  # 加群信息配置
  QQ:
    qqgroup: 752146272
    addgroupUrl : https://shang.qq.com/wpa/qunwpa?idkey=875408aae56499d92ddcdda3966fa7c01e1d3b587b038d335917df7d41893170
    welcome : 欢迎加入QQ群：${parsevip.QQ.qqgroup}
  #首页播放视频链接配置
  video:
    src: http://p8b1ddiwd.bkt.clouddn.com/video/sugar.mp4 
  # 插件安装配置
  install:
    src: http://p8b1ddiwd.bkt.clouddn.com/resources/插件安装包.zip
  # QQ登录配置
  QQLogin: 
    appId: 应用的appId
    redirecturi: 回调地址

admin:
  name: VIP资源解析 # 后台名字
  address: admin #后台前缀
  defaultImg: images/face.jpg #默认头像
  author: java_派大星 #开发作者


