######################上线环境################

###########spring配置##########
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.64.253:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    data-username: root
    data-password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
########静态资源访问配置##############
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

  thymeleaf:
    cache: false #开启模板热部署
    

#########################自定义配置#################################
#############使用：${parsevip.QQ.qqgroup}##############################
parsevip:
  # 加群信息配置
  QQ:
    qqgroup: 752146272
    addgroupUrl : https://shang.qq.com/wpa/qunwpa?idkey=875408aae56499d92ddcdda3966fa7c01e1d3b587b038d335917df7d41893170
    welcome : 欢迎加入QQ群：${parsevip.QQ.qqgroup}
  #首页播放视频链接配置
  video:
    src: http://p8b1ddiwd.bkt.clouddn.com/video/sugar.mp4 
  # 插件安装配置
  install:
    src: http://p8b1ddiwd.bkt.clouddn.com/resources/插件安装包.zip
  # QQ登录配置
  QQLogin:
    appId: 101472011
    redirecturi: http://mxspvip.cn/index
